export enum DataType {
  BIG_DECIMAL = 'BIG_DECIMAL',
  BOOLEAN = 'BOOLEAN',
  INTEGER = 'INTEGER',
  DOUBLE = 'DOUBLE',
  LOCAL_DATE = 'LOCAL_DATE',
  LOCAL_DATETIME = 'LOCAL_DATETIME',
  VARCHAR = 'VARCHAR'
}
